
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/standard?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456


  jpa:
    database: mysql
    show-sql: true


  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

